package services

import "github.com/fonteeBoa/go-log-guardian/pkg/domain"

// function is a Go function that takes in a priority, functionName, genericErrMsg, and errMsg as parameters.
//
// It calls the Debug function with the provided priority, genericErrMsg, and errMsg arguments.
// Then it returns a new LogFunction struct by calling the NewFunctionLog function with the provided priority, functionName, genericErrMsg, and errMsg arguments.
func Function(priority domain.Priority, functionName string, genericErrMsg string, errMsg string) domain.LogFunction {
	Debug(priority, genericErrMsg, errMsg)
	return NewFunctionLog(priority, functionName, genericErrMsg, errMsg)
}

// database generates a new database log and returns it.
//
// Parameters:
// - priority: the priority of the log.
// - tableName: the name of the table to log to.
// - query: the query to execute.
// - genericErrMsg: the generic error message.
// - errMsg: the specific error message.
//
// Returns:
// - domain.LogDatabase: the generated database log.
func Database(priority domain.Priority, tableName string, query string, genericErrMsg string, errMsg string) domain.LogDatabase {
	Debug(priority, genericErrMsg, errMsg)
	return NewDatabaseLog(priority, tableName, query, genericErrMsg, errMsg)
}

// request generates a new request log with the provided parameters.
//
// Parameters:
//   - priority: The priority of the request.
//   - method: The HTTP method of the request.
//   - statusCode: The HTTP status code of the response.
//   - path: The path of the request.
//   - responseSize: The size of the response in bytes.
//   - genericErrMsg: The generic error message.
//   - errMsg: The specific error message.
//
// Returns:
//   - domain.LogRequest: The generated request log.
func Request(priority domain.Priority, method string, statusCode int, path string, responseSize int, genericErrMsg string, errMsg string) domain.LogRequest {
	Debug(priority, genericErrMsg, errMsg)
	return NewRequestLog(priority, method, statusCode, path, responseSize, genericErrMsg, errMsg)
}

// details generates log details based on the given priority, generic error message, and error message.
// It calls the Debug function and returns the log details generated by the NewLogDetails function.
//
// Parameters:
// - priority: the priority level of the log details.
// - genericErrMsg: the generic error message to be included in the log details.
// - errMsg: the specific error message to be included in the log details.
//
// Return type:
// - domain.LogDetails: the log details generated by the NewLogDetails function.
func Details(priority domain.Priority, genericErrMsg string, errMsg string) domain.LogDetails {
	Debug(priority, genericErrMsg, errMsg)
	return NewLogDetails(priority, genericErrMsg, errMsg)
}
